services:
  redis:
    image: redis:alpine
    ports:
    - "${REDIS_PORT}:${REDIS_PORT}"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
  postgres:
    image: postgres:12
    environment:
      POSTGRES_NAME: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data