services:
  redis:
    image: redis:alpine
    ports:
    - "${REDIS_PORT}:${REDIS_PORT}"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
  postgres:
    image: postgres:12
    environment:
      POSTGRES_NAME: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
    - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data