"""delete amount from deposits and currency_invests tables

Revision ID: 08c1e5912e37
Revises: 8f89689b592d
Create Date: 2024-10-28 12:09:48.704888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c1e5912e37'
down_revision: Union[str, None] = '8f89689b592d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency_invests', 'purchase_amount')
    op.drop_column('deposits', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('currency_invests', sa.Column('purchase_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
