"""delete account_id from deposits, asset and currency_invests tables

Revision ID: 0d476afc938b
Revises: 08c1e5912e37
Create Date: 2024-11-04 12:39:57.657910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d476afc938b'
down_revision: Union[str, None] = '08c1e5912e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assets_account_id_fkey', 'assets', type_='foreignkey')
    op.drop_column('assets', 'account_id')
    op.drop_constraint('currency_invests_account_id_fkey', 'currency_invests', type_='foreignkey')
    op.drop_column('currency_invests', 'account_id')
    op.drop_constraint('deposits_account_id_fkey', 'deposits', type_='foreignkey')
    op.drop_column('deposits', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('deposits_account_id_fkey', 'deposits', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.add_column('currency_invests', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('currency_invests_account_id_fkey', 'currency_invests', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.add_column('assets', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('assets_account_id_fkey', 'assets', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
