"""change default balance_investable_funds to 0.00

Revision ID: 5ed61dd8c6d0
Revises: ee8f4d6c0459
Create Date: 2024-10-16 12:36:48.074924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed61dd8c6d0'
down_revision: Union[str, None] = 'ee8f4d6c0459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
