"""delete currency from transactions tables

Revision ID: 709a4236295b
Revises: 0d476afc938b
Create Date: 2024-11-04 12:53:28.091348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709a4236295b'
down_revision: Union[str, None] = '0d476afc938b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency_invests', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_invests', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
