"""add currency to currency_invests tables

Revision ID: 79729ea66f01
Revises: 709a4236295b
Create Date: 2024-11-04 13:31:26.608738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79729ea66f01'
down_revision: Union[str, None] = '709a4236295b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_invests', sa.Column('currency', sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency_invests', 'currency')
    # ### end Alembic commands ###
